In [1]:
# Import dependencies
import pandas as pd
import os
import random

import gmaps
import gmaps.datasets
from config import g_key

In [2]:
gmaps.configure(api_key=g_key)

In [3]:
# Import the WeatherPy_vacation.csv file as a new DataFrame
infolder = "weather_data"
infile   = "WeatherPy_vacation.csv"

vacation_df = pd.read_csv(os.path.join(infolder,infile))

From the vacation search map, choose at least four cities in close proximity on your map that are on the same continent that a customer might travel to, and then create a directions layer map.

In [4]:
# Get number of entries for each country
vacation_df["Country"].value_counts()

US    17
BR    14
ID    13
MX     9
PG     8
      ..
CO     1
GW     1
YE     1
KM     1
GY     1
Name: Country, Length: 62, dtype: int64

In [5]:
# Select only cities in the US
us_vacation_df = vacation_df[vacation_df["Country"]== "US"].copy().reset_index(drop=True)
us_vacation_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Saint Anthony,US,75.00,overcast clouds,45.02,-93.22,Holiday Inn Express Roseville-St. Paul
1,Las Cruces,US,81.00,clear sky,32.31,-106.78,SpringHill Suites by Marriott Las Cruces
2,Kahului,US,78.80,few clouds,20.89,-156.47,Maui Seaside Hotel
3,Albany,US,77.00,scattered clouds,42.60,-73.97,NaN
4,Jamestown,US,84.99,clear sky,42.10,-79.24,Hampton Inn & Suites Jamestown
5,Crossville,US,84.00,few clouds,35.95,-85.03,Hampton Inn Crossville
6,Kapaa,US,77.00,scattered clouds,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
7,Silver City,US,75.20,clear sky,32.77,-108.28,Copper Manor Motel
8,Merrill,US,77.00,scattered clouds,45.18,-89.68,Prairie Motel
9,Avera,US,82.99,broken clouds,33.19,-82.53,NaN
10,Lavaca,US,84.99,overcast clouds,28.61,-96.63,Holiday Inn Express & Suites Port Lavaca
11,Broome,US,78.01,clear sky,42.25,-75.83,Chenango Valley State Park
12,Medford,US,77.00,clear sky,42.33,-122.88,Hampton Inn Medford
13,Marathon,US,75.99,clear sky,44.90,-89.77,NaN
14,Saint George,US,75.20,clear sky,37.10,-113.58,Best Western Plus Abbey Inn
15,Williamsport,US,77.00,broken clouds,41.24,-77.00,Hampton Inn Williamsport-Downtown
16,Deming,US,80.60,clear sky,32.27,-107.76,Best Western Deming Southwest Inn

In [6]:
def analyse_row(**row):
    #if row["Hotel Name"].isnull():
    #    return False
    #else:
    #    return True
    print(row["City"])

In [7]:
for index, row in us_vacation_df.iterrows():
    # print(type(row))
    # print(row["City"])
    analyse_row(**row)

Saint Anthony
Las Cruces
Kahului
Albany
Jamestown
Crossville
Kapaa
Silver City
Merrill
Avera
Lavaca
Broome
Medford
Marathon
Saint George
Williamsport
Deming

In [8]:
# Drop cities where the hotel name is NaN
us_vacation_df.dropna(inplace=True)
us_vacation_df.reset_index(drop=True,inplace=True)
us_vacation_df.sort_values(["Lat","Lng"],inplace=True)
us_vacation_df.reset_index(drop=True)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Kahului,US,78.80,few clouds,20.89,-156.47,Maui Seaside Hotel
1,Kapaa,US,77.00,scattered clouds,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
2,Lavaca,US,84.99,overcast clouds,28.61,-96.63,Holiday Inn Express & Suites Port Lavaca
3,Deming,US,80.60,clear sky,32.27,-107.76,Best Western Deming Southwest Inn
4,Las Cruces,US,81.00,clear sky,32.31,-106.78,SpringHill Suites by Marriott Las Cruces
5,Silver City,US,75.20,clear sky,32.77,-108.28,Copper Manor Motel
6,Crossville,US,84.00,few clouds,35.95,-85.03,Hampton Inn Crossville
7,Saint George,US,75.20,clear sky,37.10,-113.58,Best Western Plus Abbey Inn
8,Williamsport,US,77.00,broken clouds,41.24,-77.00,Hampton Inn Williamsport-Downtown
9,Jamestown,US,84.99,clear sky,42.10,-79.24,Hampton Inn & Suites Jamestown
10,Broome,US,78.01,clear sky,42.25,-75.83,Chenango Valley State Park
11,Medford,US,77.00,clear sky,42.33,-122.88,Hampton Inn Medford
12,Saint Anthony,US,75.00,overcast clouds,45.02,-93.22,Holiday Inn Express Roseville-St. Paul
13,Merrill,US,77.00,scattered clouds,45.18,-89.68,Prairie Motel

In [9]:
# Pick 5 US cities at random

city_index = [9,10,12,13] 

vacation_itinerary = us_vacation_df.iloc[city_index].copy()
vacation_itinerary.reset_index(drop=True,inplace=True)
vacation_itinerary

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Jamestown,US,84.99,clear sky,42.10,-79.24,Hampton Inn & Suites Jamestown
1,Broome,US,78.01,clear sky,42.25,-75.83,Chenango Valley State Park
2,Saint Anthony,US,75.00,overcast clouds,45.02,-93.22,Holiday Inn Express Roseville-St. Paul
3,Merrill,US,77.00,scattered clouds,45.18,-89.68,Prairie Motel

In [10]:
# Create separate DataFrames for each city
cities_dfs = []

for index in range(vacation_itinerary.shape[0]):
    cities_dfs.append(vacation_itinerary.iloc[index].copy())

In [20]:
# 
fig = gmaps.figure()

from_lat_lng = (cities_dfs[0]["Lat"],cities_dfs[0]["Lng"])
to_lat_lng = (cities_dfs[3]["Lat"],cities_dfs[3]["Lng"])
waypoints = [(cities_dfs[i]["Lat"],cities_dfs[i]["Lng"]) for i in range(1,len(cities_dfs)-1)]
    
layer = gmaps.directions_layer(from_lat_lng, to_lat_lng, waypoints=waypoints, travel_mode='DRIVING')
fig.add_layer(layer)
    
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
fig = gmaps.figure()

locations = vacation_itinerary[["Lat","Lng"]]

print(locations)

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in vacation_itinerary.iterrows()]

# Create then show the marker layer on the Google map
marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(marker_layer)

fig

     Lat    Lng
0  42.10 -79.24
1  42.25 -75.83
2  45.02 -93.22
3  45.18 -89.68

Figure(layout=FigureLayout(height='420px'))